name: big-bear-pihole
services:
  app:
    cpu_shares: 90
    command: []
    container_name: big-bear-pihole
    deploy:
      resources:
        limits:
          memory: 907M
    environment:
      - TZ=Europe/Madrid
      - WEBPASSWORD=ziripot68
    hostname: big-bear-pihole
    image: pihole/pihole:2024.07.0
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pi-hole.png
    ports:
      - mode: ingress
        target: 53
        published: "53"
        protocol: tcp
      - mode: ingress
        target: 53
        published: "53"
        protocol: udp
      - mode: ingress
        target: 67
        published: "67"
        protocol: udp
      - mode: ingress
        target: 443
        published: "10443"
        protocol: tcp
      - target: 80
        published: "5380"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/big-bear-pihole/etc
        target: /etc/pihole
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/big-bear-pihole/dnsmasq.d
        target: /etc/dnsmasq.d
        bind:
          create_host_path: true
    x-casaos:
      ports:
        - container: "53"
          description:
            en_us: "Container Port: 53"
        - container: "67"
          description:
            en_us: "Container Port: 67"
        - container: "80"
          description:
            en_us: "Container Port: 80"
        - container: "443"
          description:
            en_us: "Container Port: 443"
      volumes:
        - container: /etc/pihole
          description:
            en_us: "Container Path: /etc/pihole"
        - container: /etc/dnsmasq.d
          description:
            en_us: "Container Path: /etc/dnsmasq.d"
    devices: []
    cap_add: []
    networks:
      - pihole-network
    privileged: false
networks:
  pihole-network:
    name: big-bear-pihole_pihole-network
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  author: BigBearTechWorld
  category: BigBearCasaOS
  description:
    en_us: The Pi-hole® is a DNS sinkhole that protects your devices from unwanted
      content without installing any client-side software.
  developer: pi-hole.net
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pi-hole.png
  index: /admin
  is_uncontrolled: false
  main: app
  port_map: "5380"
  scheme: http
  store_app_id: big-bear-pihole
  tagline:
    en_us: A black hole for Internet advertisements
  thumbnail: ""
  title:
    custom: ""
    en_us: Pi-hole
